# Generated by Django 5.2.12 on 2026-03-04 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.TextField(unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('indexed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
