# Generated by Django 5.2.12 on 2026-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ext',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
