# Generated by Django 5.2.12 on 2026-03-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_image_ext_image_mtime_image_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scan_path_root', models.CharField(max_length=1000, unique=True)),
                ('open_folder_unc_base', models.CharField(blank=True, help_text='Example: \\\\files\\vmstore\\Archive\\Customers', max_length=1000, null=True)),
                ('open_folder_smb_base', models.CharField(blank=True, help_text='Example: smb://files/vmstore/Archive/Customers', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('scan_path', models.CharField(default='/mnt/archive', max_length=1000)),
                ('index_batch_size', models.IntegerField(default=50)),
                ('enrich_batch_size', models.IntegerField(default=200)),
                ('scan_interval_seconds', models.IntegerField(default=900)),
                ('index_interval_seconds', models.IntegerField(default=10)),
                ('enrich_interval_seconds', models.IntegerField(default=60)),
                ('preview_size', models.IntegerField(default=512)),
                ('open_folder_unc_base', models.CharField(blank=True, help_text='Example: \\\\files\\vmstore\\Archive', max_length=1000, null=True)),
                ('open_folder_smb_base', models.CharField(blank=True, help_text='Example: smb://files/vmstore/Archive', max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexer.accessroot'),
        ),
        migrations.CreateModel(
            name='UserAccessRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.accessroot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'root')},
            },
        ),
    ]
