# Generated by Django 5.2.12 on 2026-03-05 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_accessroot_indexersettings_image_root_useraccessroot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('task', models.CharField(db_index=True, max_length=50)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
