# Generated by Django 5.2.12 on 2026-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_tasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=1500, unique=True)),
                ('done', models.BooleanField(db_index=True, default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
