# Generated by Django 5.2.12 on 2026-03-05 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0005_scandir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scandir',
            options={'ordering': ['done', 'retry_at', 'updated']},
        ),
        migrations.AddField(
            model_name='scandir',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scandir',
            name='retry_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
