# Generated by Django 5.2.12 on 2026-03-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0007_image_skip_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='file_ext',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='image',
            name='preview_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='preview_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='preview_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='preview_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_path', models.TextField()),
                ('raw_path', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('exists', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=False)),
                ('xml_file', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_documents', to='indexer.image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='indexer.image')),
            ],
            options={
                'indexes': [models.Index(fields=['source'], name='indexer_ass_source_57f6e2_idx'), models.Index(fields=['exists'], name='indexer_ass_exists_e3b147_idx'), models.Index(fields=['missing'], name='indexer_ass_missing_8fcd68_idx')],
            },
        ),
    ]
