# Generated by Django 5.2.12 on 2026-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0008_image_extracted_text_image_file_ext_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='embedding_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='embedding_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='folder_tokens',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='metadata_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='metadata_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='metadata_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='preview_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='preview_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='text_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='text_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='text_version',
            field=models.IntegerField(default=1),
        ),
    ]
