# Generated by Django 5.2.12 on 2026-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0010_image_camera_make_image_camera_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='clustered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='color_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='duplicate_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='duplicate_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='image',
            name='embedding_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='extracted_text_clean',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='file_ctime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='folder_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='is_primary_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='metadata_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='near_duplicate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='orientation',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='phash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='image',
            name='probable_job_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='relative_dir',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='image',
            name='similar_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='similarity_anchor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='text_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='text_engine',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='text_language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='text_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='text_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='text_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='visual_cluster_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_ext',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='indexed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='metadata_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='preview_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='skip_index',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
    ]
