# Generated by Django 5.2.12 on 2026-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0011_image_aspect_ratio_image_bit_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='metadata_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=20),
        ),
    ]
