# Generated by Django 5.2.12 on 2026-03-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0012_alter_image_embedding_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(db_index=True)),
                ('rel_path', models.TextField(blank=True, db_index=True, default='')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('depth', models.IntegerField(db_index=True, default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('has_children', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('probable_job_number', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indexer.folder')),
                ('preview_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indexer.image')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='indexer.accessroot')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='indexer.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['root', 'parent', 'name'], name='indexer_fol_root_id_8a58de_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['root', 'depth'], name='indexer_fol_root_id_615102_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['root', 'has_children'], name='indexer_fol_root_id_bcf0c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('root', 'path')},
        ),
    ]
