# Generated by Django 5.2.12 on 2026-03-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0013_folder_image_folder_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['skip_index', 'preview_status', 'id'], name='img_prev_q_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['skip_index', 'text_status', 'preview_status', 'id'], name='img_text_q_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['skip_index', 'embedding_status', 'preview_status', 'id'], name='img_embed_q_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['skip_index', 'metadata_status', 'id'], name='img_meta_q_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['indexed', 'skip_index', 'id'], name='img_index_q_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['root', 'customer_name'], name='img_root_cust_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['root', 'probable_job_number'], name='img_root_job_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['root', 'folder', 'id'], name='img_root_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['duplicate_group', 'is_primary_duplicate'], name='img_dupe_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='scandir',
            index=models.Index(fields=['done', 'retry_at', 'updated'], name='scandir_queue_idx'),
        ),
    ]
