# Generated by Django 5.2.12 on 2026-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0017_alter_folderhealthsnapshot_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='archivestats',
            new_name='indexer_arc_scope_81f5ba_idx',
            old_name='archstats_scope_idx',
        ),
        migrations.AlterField(
            model_name='archivestats',
            name='scope',
            field=models.CharField(default='global', max_length=32, unique=True),
        ),
    ]
