# Generated by Django 5.2.12 on 2026-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0026_add_image_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
