from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0028_sqlite_rebuild_archivestats_without_legacy_text_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_filename", models.CharField(blank=True, default="", max_length=500)),
                ("source_path", models.TextField(blank=True, default="")),
                ("file_ext", models.CharField(blank=True, db_index=True, default="", max_length=20)),
                ("mime_type", models.CharField(blank=True, default="", max_length=120)),
                ("sha256", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("document_type", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("correspondent", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("ocr_text", models.TextField(blank=True, default="")),
                ("ocr_text_preview", models.TextField(blank=True, default="")),
                ("extracted_text_clean", models.TextField(blank=True, default="")),
                ("extracted_text_search", models.TextField(blank=True, default="")),
                ("extracted_text_summary", models.TextField(blank=True, default="")),
                ("text_source", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("text_engine", models.CharField(blank=True, default="", max_length=50)),
                ("text_confidence", models.FloatField(blank=True, null=True)),
                ("text_length", models.IntegerField(default=0)),
                ("text_language", models.CharField(blank=True, default="", max_length=20)),
                ("detected_emails", models.JSONField(blank=True, default=list)),
                ("detected_phones", models.JSONField(blank=True, default=list)),
                ("detected_dates", models.JSONField(blank=True, default=list)),
                ("detected_money", models.JSONField(blank=True, default=list)),
                ("detected_keywords", models.JSONField(blank=True, default=list)),
                ("invoice_number", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("invoice_total", models.CharField(blank=True, default="", max_length=64)),
                ("invoice_due_date", models.CharField(blank=True, default="", max_length=64)),
                ("invoice_vendor", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("duplicate_group", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("is_duplicate", models.BooleanField(db_index=True, default=False)),
                ("confidence_score", models.FloatField(default=0)),
                ("review_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("needs_review", "Needs Review")], db_index=True, default="pending", max_length=16)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("ok", "OK"), ("error", "Error")], db_index=True, default="pending", max_length=16)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="document", to="indexer.image")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_documents", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="InboundEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_message_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("imap_uid", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("mailbox", models.CharField(blank=True, db_index=True, default="INBOX", max_length=255)),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                ("from_email", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("to_emails", models.TextField(blank=True, default="")),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body_text", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processed", "Processed"), ("error", "Error")], db_index=True, default="pending", max_length=16)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-received_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_number", models.PositiveIntegerField()),
                ("text_raw", models.TextField(blank=True, default="")),
                ("extracted_text_clean", models.TextField(blank=True, default="")),
                ("extracted_text_search", models.TextField(blank=True, default="")),
                ("text_summary", models.TextField(blank=True, default="")),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="indexer.document")),
            ],
            options={"ordering": ["page_number"], "unique_together": {("document", "page_number")}},
        ),
        migrations.CreateModel(
            name="InboundEmailAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(blank=True, default="", max_length=500)),
                ("content_type", models.CharField(blank=True, default="", max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_attachments", to="indexer.document")),
                ("email", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="indexer.inboundemail")),
                ("image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_attachments", to="indexer.image")),
            ],
        ),
        migrations.AddIndex(model_name="document", index=models.Index(fields=["document_type", "review_status"], name="doc_type_rev_idx")),
        migrations.AddIndex(model_name="document", index=models.Index(fields=["sync_status", "review_status"], name="doc_sync_rev_idx")),
        migrations.AddIndex(model_name="document", index=models.Index(fields=["duplicate_group", "is_duplicate"], name="doc_dupe_grp_idx")),
        migrations.AddIndex(model_name="document", index=models.Index(fields=["invoice_vendor", "invoice_number"], name="doc_inv_vendor_idx")),
        migrations.AddIndex(model_name="inboundemail", index=models.Index(fields=["status", "received_at"], name="mail_status_recv_idx")),
        migrations.AddIndex(model_name="inboundemail", index=models.Index(fields=["from_email", "received_at"], name="mail_from_recv_idx")),
    ]
