# Generated by Django 5.2.12 on 2026-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0029_documents_and_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='control_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='embedding_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='mail_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='metadata_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='ocr_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='ops_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='preview_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='queue_snapshot_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='scan_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='text_queue_depth',
            field=models.BigIntegerField(default=0),
        ),
    ]
