# Generated by Django 5.2.12 on 2026-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0030_queuehealthsnapshot_control_queue_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='celery_queue_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='document_sync_queue_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuehealthsnapshot',
            name='ocr_dispatch_queue_depth',
            field=models.IntegerField(default=0),
        ),
    ]
