"""
Django settings for media_index project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, "1" if default else "0").strip().lower() in {"1", "true", "yes", "on"}


SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-s@gpk*%szx)h7027xvx2u=j#*=6ykr@&)p^se%(5spda(ndl6y",
)

DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")
    if host.strip()
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "indexer",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "indexer.trusted_proxy.TrustedProxyCsrfBypassMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "indexer.trusted_proxy.TrustedProxyUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "media_index.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "media_index.wsgi.application"


# Database
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").strip().lower()

if DB_ENGINE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "media_index"),
            "USER": os.getenv("POSTGRES_USER", "media_index_user"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.getenv("POSTGRES_CONN_MAX_AGE", "300")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3")),
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("TIME_ZONE", "America/Chicago")
USE_I18N = True
USE_TZ = True

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/"


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media"))

STUDIO_PROXY_SHARED_SECRET = os.getenv("STUDIO_PROXY_SHARED_SECRET", "").strip()
STUDIO_PROXY_USERNAME = os.getenv("STUDIO_PROXY_USERNAME", "studio_proxy").strip()

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

IMAP_HOST = os.getenv("IMAP_HOST", "")
IMAP_PORT = int(os.getenv("IMAP_PORT", "993"))
IMAP_USERNAME = os.getenv("IMAP_USERNAME", "")
IMAP_PASSWORD = os.getenv("IMAP_PASSWORD", "")
IMAP_MAILBOX = os.getenv("IMAP_MAILBOX", "INBOX")
IMAP_USE_SSL = env_bool("IMAP_USE_SSL", default=True)

FORCE_SCRIPT_NAME = "/ai"
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1"))
CELERY_TASK_ACKS_LATE = env_bool("CELERY_TASK_ACKS_LATE", default=True)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 20
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500000
CELERY_TASK_TIME_LIMIT = 1800
CELERY_TASK_SOFT_TIME_LIMIT = 1500

CELERY_BEAT_SCHEDULE = {
    "scan-archive-every-100-seconds": {
        "task": "indexer.tasks.scan_task",
        "schedule": 100.0,
        "args": (),
        "options": {"queue": "scan", "routing_key": "scan"},
    },
    "queue-previews-every-30-sec": {
        "task": "indexer.tasks_preview.queue_missing_previews_task",
        "schedule": 30.0,
        "args": (64, 8),
        "options": {"queue": "preview", "routing_key": "preview"},
    },
    "queue-text-every-60-sec": {
        "task": "indexer.tasks_text.queue_missing_text_task",
        "schedule": 60.0,
        "args": (1000,),
        "options": {"queue": "ocr", "routing_key": "ocr"},
    },
    "queue-embeddings-every-60-sec": {
        "task": "indexer.tasks_embedding.queue_missing_embeddings_task",
        "schedule": 60.0,
        "args": (256, 16),
        "options": {"queue": "control", "routing_key": "control"},
    },
    "queue-metadata-every-120-sec": {
        "task": "indexer.tasks_metadata.queue_missing_metadata_task",
        "schedule": 120.0,
        "args": (512, 32),
        "options": {"queue": "control", "routing_key": "control"},
    },
    "queue-dedupe-every-90-sec": {
        "task": "indexer.tasks_dedupe.queue_missing_dedupe_task",
        "schedule": 90.0,
        "args": (500,),
        "options": {"queue": "control", "routing_key": "control"},
    },
    "repair-missing-previews-every-5-min": {
        "task": "indexer.tasks_preview_repair.repair_missing_previews_task",
        "schedule": 300.0,
        "args": (500,),
        "options": {"queue": "preview", "routing_key": "preview"},
    },
    "repair-missing-previews-every-30-min": {
        "task": "indexer.tasks_preview.repair_missing_previews_task",
        "schedule": 1800.0,
        "args": (500,),
        "options": {"queue": "preview", "routing_key": "preview"},
    },
    "reset-stuck-preview-every-10-min": {
        "task": "indexer.tasks_recovery.reset_stale_preview_processing_task",
        "schedule": 600.0,
        "args": (45,),
        "options": {"queue": "preview", "routing_key": "preview"},
    },
    "reset-stuck-processing-every-10-min": {
        "task": "indexer.tasks_recovery.reset_stale_processing_task",
        "schedule": 300.0,
        "args": (45,),
        "options": {"queue": "control", "routing_key": "control"},
    },
    "rebuild_archive_stats": {
        "task": "indexer.tasks_stats.rebuild_archive_stats_task",
        "schedule": 240.0,
        "options": {"queue": "ops", "routing_key": "ops"},
    },
    "rebuild_queue_health_snapshot": {
        "task": "indexer.tasks_queue_health.rebuild_queue_health_snapshot_task",
        "schedule": 240.0,
        "args": (45,),
        "options": {"queue": "ops", "routing_key": "ops"},
    },
    "rebuild_folder_health_snapshot": {
        "task": "indexer.tasks_folder_health.rebuild_folder_health_snapshot_task",
        "schedule": 300.0,
        "options": {"queue": "ops", "routing_key": "ops"},
    },
    "queue-document-sync-every-90-sec": {
        "task": "indexer.tasks_documents.queue_missing_document_sync_task",
        "schedule": 90.0,
        "args": (500, 50),
        "options": {"queue": "ocr", "routing_key": "ocr"},
    },
    "fetch-imap-emails-every-5-min": {
        "task": "indexer.tasks_mail.fetch_imap_emails",
        "schedule": 300.0,
        "options": {"queue": "mail", "routing_key": "mail"},
    },
}

CELERY_TASK_ROUTES = {
    "indexer.tasks.scan_task": {"queue": "scan"},



    "indexer.tasks_stats.rebuild_archive_stats_task": {"queue": "ops"},
    "indexer.tasks_queue_health.rebuild_queue_health_snapshot_task": {"queue": "ops"},
    "indexer.tasks_folder_health.rebuild_folder_health_snapshot_task": {"queue": "ops"},


    "indexer.tasks_documents.queue_missing_document_sync_task": {"queue": "ocr"},
    "indexer.tasks_documents.sync_document_from_image_task": {"queue": "ocr"},
    "indexer.tasks_documents.reprocess_document_task": {"queue": "ocr"},
    "indexer.tasks_text.queue_missing_text_task": {"queue": "ocr"},
    
    "indexer.tasks_text.extract_text_task": {"queue": "text"},
    
    "indexer.tasks_mail.fetch_imap_emails": {"queue": "mail"},
    "indexer.tasks_mail.relink_email_documents_task": {"queue": "mail"},

    
    
    "indexer.tasks_embedding.queue_missing_embeddings_task": {"queue": "control"},
    "indexer.tasks_metadata.queue_missing_metadata_task": {"queue": "control"},
    "indexer.tasks_dedupe.queue_missing_dedupe_task": {"queue": "control"},
    "indexer.tasks_recovery.reset_stale_processing_task": {"queue": "control"},

    "indexer.tasks_preview.queue_missing_previews_task": {"queue": "preview"},
    "indexer.tasks_preview.process_preview_task": {"queue": "preview"},
    "indexer.tasks_preview.process_preview_batch_task": {"queue": "preview"},
    "indexer.tasks_preview_repair.repair_missing_previews_task": {"queue": "preview"},
    "indexer.tasks_recovery.reset_stale_preview_processing_task": {"queue": "preview"},

    

    "indexer.tasks_embedding.embed_image_task": {"queue": "embedding"},
    "indexer.tasks_embedding.process_embedding_batch_task": {"queue": "embedding"},

    "indexer.tasks_metadata.extract_metadata_task": {"queue": "metadata"},
    "indexer.tasks_metadata.process_metadata_batch_task": {"queue": "metadata"},
    "indexer.tasks_dedupe.dedupe_image_task": {"queue": "metadata"},
    "indexer.tasks_duplicate_groups.refresh_duplicate_groups_task": {"queue": "metadata"},



}

CELERY_TASK_ANNOTATIONS = {
    "indexer.tasks_preview.process_preview_task": {
        "soft_time_limit": 300,
        "time_limit": 360,
    },
    "indexer.tasks_preview.process_preview_batch_task": {
        "soft_time_limit": 600,
        "time_limit": 720,
    },
    "indexer.tasks_text.extract_text_task": {
        "soft_time_limit": 300,
        "time_limit": 360,
    },
    "indexer.tasks_metadata.extract_metadata_task": {
        "soft_time_limit": 180,
        "time_limit": 240,
    },
    "indexer.tasks_embedding.embed_image_task": {
        "soft_time_limit": 300,
        "time_limit": 360,
    },
    "indexer.tasks_documents.sync_document_from_image_task": {
        "soft_time_limit": 300,
        "time_limit": 360,
    },
}

INDEX_PREVIEW_ROOT = os.getenv("INDEX_PREVIEW_ROOT", "/mnt/ai-previews/development")
INDEX_PREVIEW_MOUNT_CHECK = os.getenv("INDEX_PREVIEW_MOUNT_CHECK", "/mnt/ai-previews")

SCAN_PATH = os.getenv("SCAN_PATH", "/mnt/archive")
QDRANT_URL = os.getenv("QDRANT_URL", "http://127.0.0.1:6333")
QDRANT_COLLECTION = os.getenv("QDRANT_COLLECTION", "images")